---
title: "network statistics (part 2)"
author: "Nicholas Horton (nhorton@amherst.edu)"
date: "May 30, 2018"
output:
  pdf_document:
    fig_height: 5
    fig_width: 7
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mdsr)   # Load additional packages here 
require(RMySQL)
require(leaflet)

# Some customization.  You can alter or delete as desired (if you know what you are doing).
trellis.par.set(theme=theme.mosaic()) # change default color scheme for lattice
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

Proceed even with warnings...
```{r eval=TRUE}
knitr::opts_chunk$set(error = TRUE)
```

### More flights

What does the Southwest Airlines (code `WN`) route network look like in 2013?

```{r warning=FALSE}
db <- src_scidb("airlines")
flights <- tbl(db, "flights")
carriers <- tbl(db, "carriers")
airports <- tbl(db, "airports")
```

```{r warning=FALSE, cache=TRUE}
my_carrier <- "WN"
my_year <- 2013
destinations <- flights %>%
  filter(year == my_year, carrier == my_carrier) %>%
  left_join(airports, by = c("dest" = "faa")) %>%
  group_by(dest) %>%
  summarize(N = n(), lon = max(lon), lat = max(lat),
            # note use of MySQL syntax instead of dplyr
            name = min(CONCAT("(", dest, ") ",
              REPLACE(name, " Airport", "")))) %>%
  collect() %>% 
  na.omit()
glimpse(destinations)
segments <- flights %>%
  filter(year == my_year, carrier == my_carrier) %>%
  group_by(origin, dest) %>% summarize(N = n()) %>%
  left_join(airports, by = c("origin" = "faa")) %>%
  left_join(airports, by = c("dest" = "faa")) %>%
  collect() %>% na.omit()
glimpse(segments)
```



```{r warnings=FALSE}
library(ggmap)
ggmap_credentials()
route_map <- qmap("junction city, kansas", zoom = 4, maptype = "roadmap") +
  geom_point(data = destinations, alpha = 0.5,
             aes(x = lon, y = lat, size = N)) +
  scale_size() + theme_map()
route_map
```


```{r}
segments <- segments %>% arrange(desc(N))
head(segments, 4)
tail(segments, 4)
```

```{r}
oneway <- segments %>%
  filter(origin < dest, N >= 100) %>%
  rename(weights = N)
dim(oneway)
V <- select(segments, origin) %>% unique()
```

### plot the graph

```{r message=FALSE, warning=FALSE}
library(igraph)
g <- graph_from_data_frame(oneway, directed = FALSE, vertices = V)
summary(g)
#plot(g)
```

```{r}
g <- set_vertex_attr(g, "degree", value = degree(g))
gdegree <- as_data_frame(g, what = "vertices") %>%
  arrange(desc(degree)) 
head(gdegree, 3)
filter(gdegree, name == "BDL")
tail(gdegree, 3)
```

